// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the "Change Firebase Project" command.
export const firebaseConfig = {
  "projectId": "studio-7795971203-740c0",
  "appId": "1:81216379419:web:abd97e62b90c914bf436be",
  "apiKey": "AIzaSyBYhB2aUkH98PP99owprQcgDm295oniVqg",
  "authDomain": "studio-7795971203-740c0.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "81216379419",
  "storageBucket": "studio-7795971203-740c0.appspot.com"
};
